import { Salad, Sandwich } from "lucide-react";

const MenuData = {
  HotelSpecial: [
    {
      id: 1,
      name: "Mutton Special Thali",
      price: 450,
      image: "https://content3.jdmagicbox.com/v2/comp/kolhapur/j5/0231px231.x231.241018120002.r2j5/catalogue/hotel-songadya-kalamba-kolhapur-restaurants-ceivjv5m5l.jpg"
    },
    {
      id: 2,
      name: "Chicken Thali",
      price: 300,
      image: "https://media.assettype.com/homegrown/import/facebook-51282-burrp-feature.jpg?w=1200&h=675&auto=format%2Ccompress&fit=max&enlarge=true",
    },
    {
      id: 3,
      name: "Fish special Thali",
      price: 500,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiBbCcBn3mJ2ofbOYzwDFDCZeoxwoAEk7UoQ&s",
    },
    {
      id: 4,
      name: "Special Anda Masala Thali",
      price: 200,
      image: "https://b.zmtcdn.com/data/dish_photos/d70/c4895f4a1ed583c252cc6f51b8fe5d70.jpg",
    },
    {
      id: 5,
      name: "Murga Musalam Thali",
      price: 250,
      image: "https://i.ytimg.com/vi/81aToonNyQc/maxresdefault.jpg",
    },
    {
      id: 6,
      name: "Veg Thali",
      price: 300,
      image: "https://b.zmtcdn.com/data/pictures/chains/4/20330144/71abdbc5c16724332b4e2849cd71d487.jpg?fit=around|960:500&crop=960:500;*,*",
    },
  ],
  Pizza: [
    {
      id: 1,
      name: "Margherita Pizza",
      price: 175,
      image: "https://safrescobaldistatic.blob.core.windows.net/media/2022/11/PIZZA-MARGHERITA.jpg",
    },
    {
      id: 2,
      name: "Pepperoni Pizza",
      price: 150,
      image: "https://media.istockphoto.com/id/521403691/photo/hot-homemade-pepperoni-pizza.jpg?s=612x612&w=0&k=20&c=PaISuuHcJWTEVoDKNnxaHy7L2BTUkyYZ06hYgzXmTbo=",
    },
    {
      id: 3,
      name: "Four Cheese Pizza",
      price: 80,
      image: "https://kitchenatics.com/wp-content/uploads/2020/09/Cheese-pizza-1.jpg",
    },
    {
      id: 4,
      name: "Veggies Pizza",
      price: 120,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGsO8_BXeu1PTx2mLrb7OPazuxz4hJp273FQ&s",
    },
    {
      id: 5,
      name: "BBQ Chicken Pizza",
      price: 199,
      image: "https://www.allrecipes.com/thmb/qZ7LKGV1_RYDCgYGSgfMn40nmks=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/AR-24878-bbq-chicken-pizza-beauty-4x3-39cd80585ad04941914dca4bd82eae3d.jpg",
    },
    {
      id: 6,
      name: "Hawaiian pizza",
      price: 159,
      image: "https://hips.hearstapps.com/hmg-prod/images/hawaiian-pizza-index-65f4641de4b08.jpg?crop=0.6666666666666666xw:1xh;center,top&resize=1200:*",
    },
    {
      id: 7,
      name: "Tandoori Paneer Pizza",
      price: 220,
      image: "https://cdn.indiaphile.info/wp-content/uploads/2012/10/tandooripizza-2349.jpg?width=1200&crop_gravity=center&aspect_ratio=auto&q=75",
    },
    {
      id: 8,
      name: "Cheese Burst Pizza",
      price: 180,
      image: "https://b.zmtcdn.com/data/dish_photos/efa/f284fe9684805a866d196b3a8dcc8efa.jpeg",
    },
    {
      id: 9,
      name: "Cheese corn Pizza",
      price: 169,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6xUb7SUyWKR7GEFgR-Iwkj1h5-iy7wt-2Yg&s",
    },
  ],

  Burger: [
    {
      id: 1,
      name: "Classic Beef Burger",
      price: 99,
      image: "https://searafoodsme.com/wp-content/uploads/2022/04/Beef-Burger1080x720px.jpg",
    },
    {
      id: 2,
      name: "Cheese Burger",
      price: 149,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8L3AbNQIRIrFWLm3a_GjfI_A-I0Qos8ZPcQ&s",
    },
    {
      id: 3,
      name: "Chicken Burger",
      price: 160,
      image: "https://media.istockphoto.com/id/521207406/photo/southern-country-fried-chicken-sandwich.jpg?s=612x612&w=0&k=20&c=XfttLSxEO2YAjop4Gy0CIb1L5N_OK1tTKxmkiPr3QD8=",
    },
    {
      id: 4,
      name: "Veggie Burger",
      price: 185,
      image: "https://www.shutterstock.com/image-photo/delicious-vegetarian-burger-fresh-toppings-260nw-2623526417.jpg",
    },
    {
      id: 5,
      name: "Aloo Tikki Burger",
      price: 120,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIYbfVvQ8tlU0a0QcebNp8zYyXUggQFDm6xQ&s",
    },
    {
      id: 6,
      name: "BBQ Burger",
      price: 135,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxxDEPDlN25j8MlaczpleFLzbgqaqnwgQaXw&s",
    },
    {
      id: 7,
      name: "Silders Burger",
      price: 200,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGZMJIo3_lZDx6h2iUAqsG24nR8Ps6efohHA&s",
    },
    {
      id: 8,
      name: "Double/Triple Decker Burger",
      price: 225,
      image: "https://www.savoryonline.com/app/uploads/recipes/168783/double-decker-classic-burger.jpg",
    },
    {
      id: 9,
      name: "Paneer Tikka Burger",
      price: 135,
      image: "https://jeyporedukaan.in/wp-content/uploads/2022/09/images-21.jpeg",
    },
  ],

  Noodles: [
    {
      id: 1,
      name: "Hakka Noodles",
      price: 70,
      image: "https://i0.wp.com/kitchensavouries.com/wp-content/uploads/2018/12/Vegetable-Hakka-Noodles3.jpg?resize=1024%2C683&ssl=1",
    },
    {
      id: 2,
      name: "Chowmein",
      price: 89,
      image: "https://s.lightorangebean.com/media/20240914164843/chow-mein-fun-done.png",
    },
    {
      id: 3,
      name: "Schezwan Noodles",
      price: 99,
      image: "https://static.vecteezy.com/system/resources/previews/057/713/882/large_2x/spicy-schezwan-noodles-with-red-sauce-served-in-plate-isolated-on-marble-background-side-view-of-singapore-food-photo.jpg",
    },
    {
      id: 4,
      name: "Chilli Garlic Noodles",
      price: 69,
      image: "https://www.chefkunalkapur.com/wp-content/uploads/2021/12/Veg-Chowmein-scaled.jpg?v=1638771610",
    },
    {
      id: 5,
      name: "American Chopsuey",
      price: 100,
      image: "https://www.yummytummyaarthi.com/wp-content/uploads/2022/09/american-chopsuey-1.jpeg",
    },
    {
      id: 6,
      name: "Hibachi Noodles",
      price: 89,
      image: "https://d3s8tbcesxr4jm.cloudfront.net/recipe-images/v3/hibachi-noodles/0_medium.jpg",
    },
    {
      id: 7,
      name: "Speghetti",
      price: 59,
      image: "https://images.archanaskitchen.com/images/recipes/world-recipes/pasta-recipes/Spaghetti_Pasta_Recipe_In_Creamy_Tomato_Sauce_Kids_Recipes_Made_With_Del_Monte_3_d6522012db.jpg",
    },
    {
      id: 8,
      name: "Ramen",
      price: 120,
      image: "https://asset.slimmingworld.co.uk/content/media/19130/spicy-beef-ramen-sw-800px.jpg?v1=JGXiore20qg9NNIj0tmc3TKfKw-jr0s127JqqpCA2x7sMviNgcAYh1epuS_Lqxebn9V_qusKHfwbF7MOUrAPptzBhXIUL1Xnq2Mmdvx4fOk&width=552&height=552",
    },
    {
      id: 2,
      name: "pad thai",
      price: 100,
      image: "https://assets.tmecosys.com/image/upload/t_web_rdp_recipe_584x480_1_5x/img/recipe/ras/Assets/7DE647CE-2E09-4CBE-88EE-CFFCC70D7440/Derivates/F8CA1C89-596A-4EC0-9A63-6505DDBD528C.jpg",
    },
  ],

  Moctails: [
    {
      id: 1,
      name: "Martini",
      price: 80,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfW2klUvPwU7DRKXQ7w83BEVWJV-uTQ-urEg&s",
    },
    {
      id: 2,
      name: "Old Fashioned",
      price: 100,
      image: "https://cdn.shopify.com/s/files/1/0416/5599/2469/files/old-fashioned-classic-recipe.png?v=1659714695",
    },
    {
      id: 3,
      name: "Mojito",
      price: 50,
      image: "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/mojito-cocktails-150961e.jpg",
    },
    {
      id: 4,
      name: "Margarita",
      price: 85,
      image: "https://www.ndtv.com/cooks/images/margarita-new.jpg",
    },
    {
      id: 5,
      name: "Fruity macktail",
      price: 50,
      image: "https://ichef.bbci.co.uk/food/ic/food_16x9_832/recipes/strawberry_mojito_65484_16x9.jpg",
    },
    {
      id: 6,
      name: "Non-alcoholic ",
      price: 89,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_qw1eiEHMg7GB9phbCz9iSUlabYM5cq8N_A&s",
    },
    {
      id: 7,
      name: "Fruit punche",
      price: 69,
      image: "https://mindfulmocktail.com/wp-content/uploads/2022/04/fruit-punch-mocktail-500x375.jpg",
    },
    {
      id: 8,
      name: "Virgin margarita",
      price: 99,
      image: "https://abarabove.com/wp-content/uploads/2023/01/Virgin-drink-margarita-With-a-wedge-of-lime-and-classic-salt-rim-scaled.jpg",
    },
    {
      id: 9,
      name: "Mojito mocktail",
      price: 60,
      image: "https://images.immediate.co.uk/production/volatile/sites/30/2011/07/mojito-mocktail-5adaff2.jpg",
    },
  ],

  Biryani: [
    {
      id: 1,
      name: "Hyderabadi Biryani",
      price: 200,
      image: "https://www.thehosteller.com/_next/image/?url=https%3A%2F%2Fstatic.thehosteller.com%2Fhostel%2Fimages%2Fimage.jpg%2Fimage-1744199226259.jpg&w=2048&q=75",
    },
    {
      id: 2,
      name: "Kashmiri Biryani",
      price: 120,
      image: "https://ichef.bbc.co.uk/ace/standard/1600/food/recipes/kashmiri_biryani_14589_16x9.jpg.webp",
    },
    {
      id: 2,
      name: "Kolkata Biryani",
      price: 150,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStvdZv9-9AK9epWA8duL-7yJYrvMJHvveDjQ&s",
    },
    {
      id: 2,
      name: "Mughlai Biryani",
      price: 250,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRcvgoS8UM7Ec3aWZeOyb7qRtR6gazeerogA&s",
    },
    {
      id: 2,
      name: "Awadhi Biryani",
      price: 150,
      image: "https://www.bigbasket.com/media/uploads/recipe/w-l/2153_1_1.jpg",
    },
    {
      id: 2,
      name: "Beary Biryani",
      price: 99,
      image: "https://jyokitchen607760324.wordpress.com/wp-content/uploads/2018/05/22219-img_8799.jpg?w=1424&h=1066",
    },
    {
      id: 2,
      name: "Culcutta Biryani",
      price: 125,
      image: "https://b.zmtcdn.com/data/pictures/chains/5/2595/6dc6c93ebf299784dc21a5fb3e5844df.jpg",
    },
    {
      id: 2,
      name: "Luchnowi Biryani",
      price: 250,
      image: "https://www.recipesaresimple.com/wp-content/uploads/2021/09/lucknowi-chicken-biryani-recipe.jpeg",
    },
    {
      id: 2,
      name: "Bombay Biryani",
      price: 200,
      image: "https://lazzatfoods.wordpress.com/wp-content/uploads/2017/01/bombay-biryani-recipe-by-shireen-anwar.jpg?w=640",
    },
  ],

  Sandwich: [
    {
      id: 1,
      name: "Club sandwich",
      price: 110,
      image: "https://ichef.bbci.co.uk/food/ic/food_16x9_1600/recipes/club_sandwich_16496_16x9.jpg",
    },
    {
      id: 2,
      name: "Grilled cheese",
      price: 85,
      image: "https://www.allrecipes.com/thmb/pnEUcAXDg5GUJ77fUDzZp41NWkE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/AR-238891-Grilled-Cheese-Sandwich-beauty-4x3-362f705972e64a948b7ec547f7b2a831.jpg",
    },
    {
      id: 3,
      name: "mayonnaise sandwich",
      price: 120,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTonN18GxQKjjOwdG6QUao44CFSQWZdAZSo3w&s",
    },
    {
      id: 4,
      name: "Bombay sandwich",
      price: 40,
      image: "https://ichef.bbci.co.uk/food/ic/food_16x9_1600/recipes/garlic_bread_bombay_76544_16x9.jpg",
    },
    {
      id: 5,
      name: "Aloo sandwich",
      price: 60,
      image: "https://i.ytimg.com/vi/wbc62-6Gq9I/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLDnYi1mbiEwGyXGeO22bi5HOW3a_g",
    },
    {
      id: 6,
      name: "Paneer sandwich",
      price: 100,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuJaWmClKYlUHS0zMwMA_ZzsY7D52UVDIJNw&s",
    },
    {
      id: 7,
      name: "Open sandwich",
      price: 85,
      image: "https://www.simplyrecipes.com/thmb/0M6OKOkME2thh0hLqAXLuXMqjQg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-Mackenzie-Sandwich-LEAD-1-91356875e7cf4f1783bb8aafa6c0483b.jpg",
    },
    {
      id: 8,
      name: "Masala Toast",
      price: 50,
      image: "https://cdn.tarladalal.com/media/recipe/method/2025/01/16/masala_toast_dsc_7396-(2)-16-185296.webp",
    },
    {
      id: 9,
      name: "Veg Mayonnaise Sandwich",
      price: 150,
      image: "https://i.ytimg.com/vi/sOGKyqn7ePY/sddefault.jpg",
    },
  ],
  Salad: [
    {
      id: 1,
      name: "Kachumber",
      price: 150,
      image: "https://www.simplyrecipes.com/thmb/TCihoMgBAszaHRNdU9WX781I2Fg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Simply-Recipes-Kachumber-Salad-LEAD-03-aa6e0ac0e5184139bcd20d7a1718f48d.jpg",
    },
    {
      id: 2,
      name: "Kosambari/Koshimbir",
      price: 185,
      image: "https://images.archanaskitchen.com/images/recipes/indian/side-dishes/indian-salad-recipes/South_Indian_Kosambari_Salad_e549616a8e.jpg",
    },
    {
      id: 2,
      name: "Laccha Pyaaz",
      price: 120,
      image: "https://www.chefkunalkapur.com/wp-content/uploads/2021/03/Laccha-Pyaz-3.jpeg?v=1621916471",
    },
    {
      id: 2,
      name: "Sprout Salads",
      price: 130,
      image: "https://www.vegrecipesofindia.com/wp-content/uploads/2013/04/moong-sprouts-salad-recipe-1.jpg",
    },
    {
      id: 2,
      name: "Chaat-Style Salads",
      price: 165,
      image: "https://www.madhuseverydayindian.com/wp-content/uploads/2024/10/vegetable-chaat-salad.jpg",
    },
    {
      id: 2,
      name: "Yogurt-Based Salads",
      price: 200,
      image: "https://www.eatingwell.com/thmb/j6_vmVEiv4gD4WFflAGVHPYvLJE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/247594-cucumber-yogurt-salad-beauty-horizontal-87018c4344004111b05e2043f0ec0c8f.jpg",
    },
    {
      id: 2,
      name: "Bean Salads",
      price: 190,
      image: "https://www.allrecipes.com/thmb/fW3XVnghYRJvKvoDctiiemYKhhE=/0x512/filters:no_upscale():max_bytes(150000):strip_icc()/AR-14169-Mexican-bean-salad-hero-4x3-fbc15c84af564387b4a46a62bc8cca89.jpg",
    },
    {
      id: 2,
      name: "Tomato Onion Salad",
      price: 50,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5NNfuY2FHyAPdDm8E17D5Vr8VZK_6cNax5Q&s",
    },
    {
      id: 2,
      name: "Spicy Chickpea Salad",
      price: 60,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlGwyxSX3rc59QZuFK_qfG-myW080x0voHSw&s",
    },
  ],

  FrenchFries: [
    {
      id: 1,
      name: "Crinkle Cut Fries",
      price: 45,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_AhKcOHAM_9jDoBZIctMhlpS9j4mr9OJ0yg&s",
    },
    {
      id: 2,
      name: "Smiley Fries",
      price: 50,
      image: "https://i.ytimg.com/vi/bfGdT1ET2DM/sddefault.jpg",
    },
    {
      id: 3,
      name: "Tater Tots",
      price: 70,
      image: "https://www.seriouseats.com/thmb/aYoOOguiwKicWMgUwMYCPVFIjPA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20220202-tater-tots-vicky-wasik-10-8bb287641ace4c1a99dcf8ccdd69a1af.jpg",
    },
    {
      id: 4,
      name: "Steak Fries",
      price: 80,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBFR5CHvlC1vp4pxKy5BZj-Khv0spaZtC3kA&s",
    },
    {
      id: 5,
      name: "Truffle Fries",
      price: 100,
      image: "https://www.thespruceeats.com/thmb/ri8ba_zHckEKdjPRhc1neyZsufE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/easy-homemade-truffle-fries-recipe-1375725-hero-02-a9d4ccb2e72544469c044f6ddd728bf3.jpg",
    },
    {
      id: 6,
      name: "Waffle Fries",
      price: 30,
      image: "https://www.allrecipes.com/thmb/uPAVo10djhHbuTnT1X0SH5OyVDk=/0x512/filters:no_upscale():max_bytes(150000):strip_icc()/7775399-waffle-fries-ddmfs-4x3-0078-b66e170430614ef2941e5f59de258556.jpg",
    },
    {
      id: 7,
      name: "Potato Wedges",
      price: 80,
      image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2020/10/potato-wedges-recipe.jpg",
    },
    {
      id: 8,
      name: "Shoestring Fries",
      price: 30,
      image: "https://www.thecookierookie.com/wp-content/uploads/2024/07/shoestring-fries-2-of-8-edited-500x375.jpg",
    },
    {
      id: 9,
      name: "Cottage Fries",
      price: 50,
      image: "https://urbanfarmie.com/wp-content/uploads/Cottage-Fries-4-1-500x375.jpg",
    },
  ],

  Milkshakes: [
    {
      id: 1,
      name: "Chocolate Milkshake",
      price: 100,
      image: "https://images.contentstack.io/v3/assets/bltcedd8dbd5891265b/bltd2f0b951708bdfce/66707638b76a9292bd908d6f/chocolate-truffle-featured-image.jpg?q=70&width=3840&auto=webp",
    },
    {
      id: 2,
      name: "Vanila Milkshake",
      price: 70,
      image: "https://www.foodandwine.com/thmb/aYv9IwIyM4EKLL0o7W1CUSfjXzU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Vanilla-Milkshake-FT-MAG-RECIPE-0325-4ad53abc27a74f7687e510cc17d28d1d.jpg",
    },
    {
      id: 3,
      name: "Strawberry Milkshake",
      price: 75,
      image: "https://assets.epicurious.com/photos/647df8cad9749492c4d5d407/1:1/w_4506,h_4506,c_limit/StrawberryMilkshake_RECIPE_053123_3599.jpg",
    },
    {
      id: 4,
      name: "Banana Milkshake",
      price: 40,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLCRmSWOXXpQ0MnkKNDHQyk7aYBKYmsL9ULw&s",
    },
    {
      id: 5,
      name: "Oreo Milkshake",
      price: 130,
      image: "https://saltandbaker.com/wp-content/uploads/2020/12/oreo-milkshake-recipe.jpg",
    },
    {
      id: 6,
      name: "Caramel Milkshake",
      price: 145,
      image: "https://www.unicornsinthekitchen.com/wp-content/uploads/2019/06/Caramel-Milkshake.jpg",
    },
    {
      id: 7,
      name: "Blueberry Milkshake",
      price: 160,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcST8R7z8v6g5RzKpm0LZhZKVTQZ7aPZIzzryA&s",
    },
    {
      id: 8,
      name: "Almond Milkshake",
      price: 180,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTzooIyVcHW0ftvkOeRx_yVk30Ffhc1-obcg&s",
    },
    {
      id: 9,
      name: "Coconut Milkshake",
      price: 60,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzcXUfMP4UKei1sMWkYgv_LQcucHP9Npyk-A&s",
    },
  ],

  SouthIndian: [
    {
      id: 1,
      name: "Idli",
      price: 50,
      image: "https://www.awesomecuisine.com/wp-content/uploads/2007/11/Idli-with-sambar-and-chutney.jpg",
    },
    {
      id: 2,
      name: "Dosa",
      price: 60,
      image: "https://delishglobe.com/wp-content/uploads/2024/09/Masala-dosa-1.png",
    },
    {
      id: 3,
      name: "Medu Vada",
      price: 40,
      image: "https://manjulaskitchen.com/wp-content/uploads/medu_vada.jpg",
    },
    {
      id: 4,
      name: "Pongal",
      price: 50,
      image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/01/pongal-ven-pongal.webp",
    },
    {
      id: 5,
      name: "Upma",
      price: 40,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTw46aSML4LeHSoPq36pB67U5ptkJBKa6mVsw&s",
    },
    {
      id: 6,
      name: "Puttu",
      price: 49,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_50-JAqMQ4lXh832o4hjbeU0Gg2igmd8-oQ&s",
    },
    {
      id: 7,
      name: "Idiyappam",
      price: 70,
      image: "https://www.awesomecuisine.com/wp-content/uploads/2008/02/idiyappam.jpg",
    },
    {
      id: 8,
      name: "Uttapam",
      price: 70,
      image: "https://www.flavouroffood.com/wp-content/uploads/2021/03/Instant-Rava-Uttapam-4.jpg",
    },
    {
      id: 9,
      name: "Appam",
      price: 80,
      image: "https://thepinchoftaste.com/assets/images/blogs/appam_2018_01_26_07_55_03.jpg",
    },
  ],

  Tacos: [
    {
      id: 1,
      name: "Chicken Tikka Tacos",
      price: 199,
      image: "https://www.savoryspiceshop.com/cdn/shop/articles/tikka-taco3.jpg?v=1760566843",
    },
    {
      id: 2,
      name: "Paneer Tacos",
      price: 249,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuTGsUJfoy0sZqVgkfuLRFdzoFNYA0zXb3vg&s",
    },
    {
      id: 3,
      name: "Keema Tacos",
      price: 249,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-8MD6YsAewzdDb_Hs8OHqJYpqHsE_4JKoQA&s",
    },
    {
      id: 4,
      name: "Aloo Gobi Tacos",
      price: 249,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKQS2bGSBTA3-UmXK0k5KVnsqjE2L0uHOvJQ&s",
    },
    {
      id: 5,
      name: "Butter Chicken/Chicken Kebab Tacos",
      price: 249,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWtbF-fMFls4thztvfMZ--uQaNQ5tEc9H6Ow&s",
    },
    {
      id: 6,
      name: "Ghee Roast Prawn Tacos",
      price: 249,
      image: "https://img-global.cpcdn.com/recipes/29ca2b8f1ddcf1ff/1200x630cq80/photo.jpg",
    },
    {
      id: 7,
      name: "Mango Glazed Chicken Tacos",
      price: 249,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTW6K-OPq-tdo8RN-HCW9UxkcOEaE7vJAcdw&s",
    },
    {
      id: 8,
      name: "Taco Chaat",
      price: 249,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaDBsttdLxzj4X-lZCwPSOwa2nE28BeCgnkA&s",
    },
    {
      id: 9,
      name: "Veggie Touch/Cheesy Veg Tacos",
      price: 249,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZvE86FkaIR6i8pc0BBp3aRnjroOGg1B4Z7A&s",
    },
  ],
  
  Waffle: [
    {
      id: 1,
      name: "Belgian Waffles",
      price: 199,
      image: "https://content.jdmagicbox.com/v2/comp/mumbai/r5/022pxx22.xx22.190116204535.h5r5/catalogue/the-belgian-waffle-co--goregaon-west-mumbai-waffle-centres-0ps2dlrmuc.jpg",
    },
    {
      id: 2,
      name: "Red Velvet Waffles",
      price: 249,
      image: "https://99pancakes.in/cdn/shop/files/Red_Velvet_waffle.jpg",
    },
    {
      id: 3,
      name: "Dark Chocolate Waffles",
      price: 249,
      image: "https://5.imimg.com/data5/YM/AB/VM/ANDROID-50220991/product-jpeg.jpg",
    },
    {
      id: 4,
      name: "Nutella & Chocolate",
      price: 249,
      image: "https://static.vecteezy.com/system/resources/previews/043/122/950/non_2x/nutella-waffle-with-chocolate-whipped-cream-knife-and-fork-served-in-dish-isolated-on-dark-background-top-view-cafe-dessert-food-photo.JPG",
    },
    {
      id: 5,
      name: "Fruity & Creamy",
      price: 249,
      image: "https://99pancakes.in/cdn/shop/files/CreamyStrawberrywaffle.jpg?v=1755018743&width=1920",
    },
    {
      id: 6,
      name: "Cookie-Based",
      price: 249,
      image: "https://images.squarespace-cdn.com/content/v1/5ea3b22556f3d073f3d9cae4/77233987-b1af-475d-bbd1-b65b2e00dd7f/IMG_0910.JPG",
    },
    {
      id: 7,
      name: "Kunafa Waffle",
      price: 249,
      image: "https://99pancakes.in/cdn/shop/files/KunafaWaffles.jpg?v=1755019850",
    },
    {
      id: 8,
      name: "Green Peas Waffles",
      price: 249,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRysjN_c21llDpr9SMTmygTmFftySCaMWl5ag&s",
    },
    {
      id: 9,
      name: "Cheesy Corn Rava Waffles",
      price: 249,
      image: "https://i.ytimg.com/vi/Pzgz6mUlisE/maxresdefault.jpg",
    },
  ],

  StreetFood: [
    {
      id: 1,
      name: "Pani puri",
      price: 79,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVxMDZ89fmuKlbqzOdXvFvhLA89V4J_klI3Q&s",
    },
    {
      id: 2,
      name: "Samosa",
      price: 20,
      image: "https://recipes.timesofindia.com/thumb/61050397.cms?width=1200&height=900",
    },
    {
      id: 3,
      name: "Kachori",
      price: 30,
      image: "https://i.ytimg.com/vi/yfDW0JrOOGI/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAJktSG7_aUDjkv9Hr56rIImD4KAQ",
    },
    {
      id: 4,
      name: "Vada pav",
      price: 20,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLY4iReJ15AUBIoW6XF1G5KocZAA3414YFBw&s",
    },
    {
      id: 5,
      name: "Bhel puri",
      price: 79,
      image: "https://www.awesomecuisine.com/wp-content/uploads/2007/11/bhel-puri-500x375.jpg",
    },
    {
      id: 6,
      name: "Chaat",
      price: 69,
      image: "https://images.archanaskitchen.com/images/recipes/snack-recipes/indian-snack-recipes/Delhi_Style_Matar_Chaat_Matra_Recipe_Spicy_Tangy_Dry_Green_Peas_Curry_Curry_Recipe_044ee2ec0c.jpg",
    },
    {
      id: 7,
      name: "Dabeli",
      price: 40,
      image: "https://recipesblob.oetker.in/assets/9447029b80054ee49f3ac21841884874/1272x764/dabeli.jpg",
    },
    {
      id: 8,
      name: "Dahi puri",
      price: 89,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlD36Chsg5iwklAQzZiRx3II-Nndwvp0uvWA&s",
    },
    {
      id: 9,
      name: "Aloo chaat",
      price: 79,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTq1ar3lm8g_hleDAXCBFlETh5HzfTMt5nmg&s",
    },
  ],

  Momos: [
    {
      id: 1,
      name: "Veg steamed Momos",
      price: 100,
      image: "https://delishglobe.com/wp-content/uploads/2025/05/Nepalese-Momo.png",
    },
    {
      id: 2,
      name: "Veg Fried Momos",
      price: 120,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT2Qy5UrTAORc804wl2NSP2eqD0RTAxXeIzg&s",
    },
    {
      id: 3,
      name: "Veg Tandoori Momos",
      price: 150,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCL03YJcVCKG-Jus56DeLolUKZFm-Xd3ZzrQ&s",
    },
    {
      id: 4,
      name: "Non-Veg Steamed Momos",
      price: 120,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtjBkSjhWbv6scblOO47N_jXwtigwdizOVNw&s",
    },
    {
      id: 5,
      name: "Non-Veg Fried Momos",
      price: 150,
      image: "https://fuddins.com/wp-content/uploads/2023/02/image_1671112223565_Chicken_Fried_Momos_6_Pcs_.jpg",
    },
    {
      id: 6,
      name: "Non-Veg Tandoori Momos",
      price: 180,
      image: "https://static.vecteezy.com/system/resources/previews/013/753/843/large_2x/tandoori-momo-veg-or-non-veg-in-red-and-cream-sauce-served-with-sauce-nepal-and-tibet-recipe-free-photo.jpg",
    },
    {
      id: 7,
      name: "Paneer Steamed Momos",
      price: 120,
      image: "https://b.zmtcdn.com/data/pictures/chains/5/2595/6dc6c93ebf299784dc21a5fb3e5844df.jpg",
    },
    {
      id: 8,
      name: "Paneer Fried Momos",
      price: 150,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6Ph3njwW9JEvQ8Ro06IzRpDzg-3OmdJb3GQ&s",
    },
    {
      id: 9,
      name: "Paneer Tandoori Momos",
      price: 160,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8JssBc1HpV9xLZlu2ua53LBGfG2ghPkj_2A&s",
    },
  ],

  Rolls: [
    {
      id: 1,
      name: "Chilli Paneer Roll",
      price: 70,
      image: "https://aartimadan.com/wp-content/uploads/2021/09/Chilli-Paneer-Roll.jpg",
    },
    {
      id: 2,
      name: "Paneer Tikka Roll",
      price: 90,
      image: "https://www.chefkunalkapur.com/wp-content/uploads/2023/08/DSC04081-scaled.jpg?v=1692276994",
    },
    {
      id: 3,
      name: "Pizza Roll",
      price: 100,
      image: "https://www.tasteofhome.com/wp-content/uploads/2018/01/Cheesy-Pizza-Rolls_EXPS_FRBZ24_198384_P2_MD_04_16_3b.jpg",
    },
    {
      id: 4,
      name: "Spicy Chole Roll",
      price: 70 ,
      image: "https://images.archanaskitchen.com/images/recipes/snack-recipes/indian-snack-recipes/Spicy_Chana_Chaat_Frankie_Recipe_a1ad716cc7.jpg",
    },
    {
      id: 5,
      name: "Cheese Roll",
      price: 85,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgY1hICt9kQcfHSY8UvEWPVxhrrjyDJKMmEw&s",
    },
    {
      id: 6,
      name: "Aloo Cheese Roll",
      price: 75,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSMGyuzwhfzAsAKrYuMMK7HKpQYzHefnsJ5A&s",
    },
    {
      id: 7,
      name: "Egg Rolls ",
      price: 50,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTClZkngYhoCXcQ6DuB9uqq6Wp5_fHaePhVVQ&s",
    },
    {
      id: 8,
      name: "Kathi Roll",
      price: 65,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlr0ST4xI-WCWr9eH6IogXXlZpJ-KJPxJfqA&s",
    },
    {
      id: 9,
      name: "Spring  Rolls",
      price: 90,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpOLVeVLfXg0JzJ3bjWTyMsvH8WexnPNyNwA&s",
    },
  ],

  Sushi: [
    {
      id: 1,
      name: "Nigiri",
      price: 199,
      image: "https://cdn.tasteatlas.com/images/dishes/ef30d84ca9f04834917378c56630c6da.jpg",
    },
    {
      id: 2,
      name: "Maki",
      price: 249,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjs8gA7WgdPgHEIEHxMGqKVvPq1ESIESFmlA&s",
    },
    {
      id: 3,
      name: "Hosomaki",
      price: 249,
      image: "https://media.istockphoto.com/id/1171918580/photo/blue-fin-tuna-roll-japanese-food.jpg?s=612x612&w=0&k=20&c=7pykt5E3DQf6lCDoYbJJyreoTXYxJsaF33Lq_POW_WM=",
    },
    {
      id: 4,
      name: "Futomak",
      price: 249,
      image: "https://www.justonecookbook.com/wp-content/uploads/2024/04/Futomaki-1344-I.jpg",
    },
    {
      id: 5,
      name: "Uramaki",
      price: 249,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZ9iMUklPEiYg8UcPAfHRTHoDuPfqTEr6WQg&s",
    },
    {
      id: 6,
      name: "Chirashi",
      price: 249,
      image: "https://www.justonecookbook.com/wp-content/uploads/2020/02/Chirashi-Sushi-7722-I-1.jpg",
    },
    {
      id: 7,
      name: "Inari",
      price: 249,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiN_afeRTy3hhixYah9RpF2ggTuDGGY4BAFg&s",
    },
    {
      id: 8,
      name: "Temaki",
      price: 249,
      image: "https://media.istockphoto.com/id/612002744/photo/salmon-temaki-ginger-and-sauce-horizontal-top-view.jpg?s=612x612&w=0&k=20&c=_SNMuUzLpa7YAiXL1XNctk5-JxfEEi4sio2qV4hExQU=",
    },
    {
      id: 9,
      name: "Oshizushi",
      price: 249,
      image: "https://media.istockphoto.com/id/1832287592/photo/three-types-of-square-pressed-sushi.jpg?s=612x612&w=0&k=20&c=dsUEqOK1emO1bHlg_ynuRShAN5WnpuqN0GHpPK_BhxU=",
    },
  ],

  Kabab: [
    {
      id: 1,
      name: "Seekh Kebab",
      price: 199,
      image: "https://media.istockphoto.com/id/501266025/photo/seekh-kabab-5.jpg?s=612x612&w=0&k=20&c=D6JXEtB4OLF9A91nAfDYLlh507LlbmP_M9PZBoJqD9Q=",
    },
    {
      id: 2,
      name: "Galouti Kebab",
      price: 249,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtEI9onGaHY4uNrGdEXolbomaHqsQkzsta2A&s",
    },
    {
      id: 3,
      name: "Shami Kebab",
      price: 249,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrp5An5IXosYgelNtGIya7__Zqw-uoPPRrxA&s",
    },
    {
      id: 4,
      name: "Kakori Kebab",
      price: 249,
      image: "https://theolddelhi.com/wp-content/uploads/2021/08/Bestsellet__Must_Try_Template_11_COMPRESSED.png",
    },
    {
      id: 5,
      name: "Reshmi Kebab",
      price: 249,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAt0vJmpMc8WMk-ZG7-DItwLpliVZglwr9hA&s",
    },
    {
      id: 6,
      name: "Hariyali Kebab",
      price: 249,
      image: "https://vaya.in/recipes/wp-content/uploads/2019/01/Hariyali-Chicken-Kabab.jpg",
    },
    {
      id: 7,
      name: "Chapli Kebab",
      price: 249,
      image: "https://www.masala.tv/wp-content/uploads/2015/07/peshawari-chapli-kabab-recipe.jpeg",
    },
    {
      id: 8,
      name: "Aloo Kebab",
      price: 249,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ2fDFvFnTP4wz9e0eWNqX3KPh3hbzL6MaYnQ&s",
    },
    {
      id: 9,
      name: "Hara Bhara Kebab",
      price: 249,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXWQ4A_Fm1HJBtxPCzBr8ZvvuC-dd7I5UTZw&s",
    },
  ],

  iceCreams: [
    {
      id: 1,
      name: "chocolate",
      price: 150,
      image: "https://media.istockphoto.com/id/153560334/photo/delicious-gourmet-chocolate-ice-cream.jpg?s=612x612&w=0&k=20&c=0V7LrfZGBHBddNmcOCCOza-mhrTV_ONtgqgK_AxExWU=",
    },
    {
      id: 2,
      name: "Vanila",
      price: 100,
      image: "https://www.foodandwine.com/thmb/QnTrAIt3aY1g4ToQEk-jULmKMsQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/vanilla-ice-cream-FT-RECIPE0324-cebca493f53c4431a0049ea65bfb4796.jpg",
    },
    {
      id: 3,
      name: "Strawberry",
      price: 80,
      image: "https://aplantifulpath.com/wp-content/uploads/2019/08/Strawberry-Ice-Cream-1.jpg",
    },
    {
      id: 4,
      name: "Mint Chocolate Chip",
      price: 175,
      image: "https://media.istockphoto.com/id/1406230986/photo/homemade-green-mint-chocolate-chip-ice-cream.jpg?s=612x612&w=0&k=20&c=cqDIFrtsKG1_LPfbtX-Zyc4s8UXKpTLYwa1l8Nro7wo=",
    },
    {
      id: 5,
      name: "Mango",
      price: 140,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQB-J--taPQ-qEJ0ZHaNZmc92kt8TmgGhHyug&s",
    },
    {
      id: 6,
      name: "Pistachio",
      price: 180,
      image: "https://jyokitchen607760324.wordpress.com/wp-content/uploads/2018/05/22219-img_8799.jpg?w=1424&h=1066",
    },
    {
      id: 7,
      name: "Raspberry",
      price: 185,
      image: "https://lmld.org/wp-content/uploads/2012/07/Raspberry-Ice-Cream-1-480x270.jpg",
    },
    {
      id: 8,
      name: "Cookies & Cream",
      price: 125,
      image: "https://www.kingarthurbaking.com/sites/default/files/styles/featured_image/public/2022-05/cookies-and-cream-ice-cream_0422.jpg?itok=-gxLG1uG",
    },
    {
      id: 9,
      name: "Butter Pecan",
      price: 100,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM5NUfIbQyZvoHtsoj6beAzvtwnRsuXaKnNw&s",
    },
  ],

  Desert: [
    {
      id: 1,
      name: "Cake",
      price: 199,
      image: "https://ocakes.in/storage/app/public/images/item/item-642f5ad0783b8.jpg",
    },
    {
      id: 2,
      name: "Pie",
      price: 249,
      image: "https://www.allrecipes.com/thmb/LM4mw4WamGcQtwvTnT9gQyFzqQU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/AR-15756-chocolate-cream-pie-4x3-1cbcc356873847ba8a86284ad08073a4.jpg",
    },
    {
      id: 3,
      name: "Pudding",
      price: 249,
      image: "https://www.yummytummyaarthi.com/wp-content/uploads/2023/05/caramel-bread-pudding-1.jpeg",
    },
    {
      id: 4,
      name: "Brownies",
      price: 249,
      image: "https://icecreambakery.in/wp-content/uploads/2024/12/Brownie-Recipe-with-Cocoa-Powder-1200x821.jpg",
    },
    {
      id: 5,
      name: "CheeseCake",
      price: 249,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6WWRrdsu3DHk_e2L0j62TrnuDdIDKQWnXUg&s",
    },
    {
      id: 6,
      name: "Cookies",
      price: 249,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5Vxi41gNCvVjNnZRBMd8COaKOVsdG6yCFDA&s",
    },
    {
      id: 7,
      name: "Tarts",
      price: 249,
      image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5Vxi41gNCvVjNnZRBMd8COaKOVsdG6yCFDA&s",
    },
    {
      id: 8,
      name: "Mousse",
      price: 249,
      image: "https://www.kingarthurbaking.com/sites/default/files/2023-06/Chocolate-Mousse_0706.jpg",
    },
    {
      id: 9,
      name: "Pancakes",
      price: 249,
      image: "https://www.inspiredtaste.net/wp-content/uploads/2025/07/Pancake-Recipe-1.jpg",
    },
  ],

};

export default MenuData;
